import reflex as rx


def header_component():
    content = rx.hstack(
        rx.hstack(
            rx.box(
                rx.hstack(
                    rx.menu.root(
                        rx.menu.trigger(
                            rx.icon(
                                "menu",
                                color="black",
                                size=27,
                            ),
                        ),
                        rx.menu.content(
                            rx.menu.item(
                                rx.icon(
                                    "user",
                                    size=15,
                                ),
                                rx.spacer(),
                                rx.text(
                                    "پروفایل",
                                    text_align="right",
                                    font_family="Vazirmatn",
                                ),
                            ),
                            rx.separator(),
                            rx.menu.item(
                                rx.icon(
                                    "scroll",
                                    size=15,
                                ),
                                rx.text(
                                    "لیست سفارشات",
                                    font_family="Vazirmatn",
                                ),
                            ),
                            rx.separator(),
                            rx.menu.item(
                                rx.icon(
                                    "log-out",
                                    size=15,
                                ),
                                rx.spacer(),
                                rx.text(
                                    "خروج",
                                    font_family="Vazirmatn",
                                ),
                            ),
                        ),
                    ),
                    rx.hstack(
                        rx.icon(
                            "shopping-basket",
                            color="black",
                            position="relative",
                            size=27,
                        ),
                        rx.text(
                            "5",
                            color="white",
                            border_radius="20px",
                            width="16px",
                            height="16px",
                            size="1",
                            background="red",
                            # align="right",
                            position="absolute",
                            display="flex",
                            justify_content="center",
                            align_items="center",
                        ),
                        width="50%",
                    ),
                    spacing="5",
                ),
            ),
            rx.box(
                rx.hstack(
                    rx.avatar(
                        fallback="MA",
                    )
                )
            ),
            justify="between",
            width=rx.breakpoints(
                initial="90%",
                sm="70%",
                lg="35%",
            ),
            align="center",
            padding="10px",
        ),
        justify="center",
        width="100%",
        bg="white",
        position="fixed",
    )
    return content
